version: "3.3"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - dwproxy_default
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - dwproxy_default
    ports:
      - "${PORT_EXPOSE_APPACHE}"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    environment:      
      - VIRTUAL_HOST=accounts.dina-web.local      
    container_name: apache
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'        
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - dwproxy_default
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "${PORT_EXPOSE_PHPMYADMIN}"    
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - dwproxy_default 
    container_name: phpmyadmin  
  keycloak:
    image: jboss/keycloak #this is the latest
    container_name: keycloak
    restart: always
    links:
      - mysql:mysql # No need for this??
    environment:
        KEYCLOAK_USER: "${KEYCLOAK_USER}"
        KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
    ports:
      - "${PORT_EXPOSE_KEYCLOAK}"
    volumes:
      - ./keycloak/configuration/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ./keycloak/themes/dina:/opt/jboss/keycloak/themes/dina  
    depends_on:
      - mysql  
    networks:
      - dwproxy_default           
volumes:
  data:
networks:
  dwproxy_default:
    driver: bridge  
